# Generated by Django 6.0.6 on 2026-07-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
