# Generated by Django 6.0.6 on 2026-07-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_metal_price_per_gram'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
