# Generated by Django 6.0.6 on 2026-07-02 11:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gender_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('target_url', models.CharField(blank=True, default='products.html', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'storefront_banners',
            },
        ),
    ]
